#!/usr/bin/env python
# -*- coding: utf-8 -*-
# from 1 to 205

from gettown import data2json


db = [{u'Value': u'33', u'Text': u'ABD'},
      {u'Value': u'166', u'Text': u'AFGANISTAN'},
      {u'Value': u'13', u'Text': u'ALMANYA'},
      {u'Value': u'17', u'Text': u'ANDORRA'},
      {u'Value': u'140', u'Text': u'ANGOLA'},
      {u'Value': u'125', u'Text': u'ANGUILLA'},
      {u'Value': u'90', u'Text': u'ANTIGUA VE BARBUDA'},
      {u'Value': u'199', u'Text': u'ARJANTIN'},
      {u'Value': u'25', u'Text': u'ARNAVUTLUK'},
      {u'Value': u'153', u'Text': u'ARUBA'},
      {u'Value': u'59', u'Text': u'AVUSTRALYA'},
      {u'Value': u'35', u'Text': u'AVUSTURYA'},
      {u'Value': u'5', u'Text': u'AZERBAYCAN'},
      {u'Value': u'54', u'Text': u'BAHAMALAR'},
      {u'Value': u'132', u'Text': u'BAHREYN'},
      {u'Value': u'177', u'Text': u'BANGLADES'},
      {u'Value': u'188', u'Text': u'BARBADOS'},
      {u'Value': u'208', u'Text': u'BELARUS'},
      {u'Value': u'11', u'Text': u'BELCIKA'},
      {u'Value': u'182', u'Text': u'BELIZE'},
      {u'Value': u'181', u'Text': u'BENIN'},
      {u'Value': u'51', u'Text': u'BERMUDA'},
      {u'Value': u'93', u'Text': u'BIRLESIK ARAP EMIRLIGI'},
      {u'Value': u'83', u'Text': u'BOLIVYA'},
      {u'Value': u'9', u'Text': u'BOSNA HERSEK'},
      {u'Value': u'167', u'Text': u'BOTSVANA'},
      {u'Value': u'146', u'Text': u'BREZILYA'},
      {u'Value': u'97', u'Text': u'BRUNEI'},
      {u'Value': u'44', u'Text': u'BULGARISTAN'},
      {u'Value': u'91', u'Text': u'BURKINA FASO'},
      {u'Value': u'154', u'Text': u'BURMA (MYANMAR)'},
      {u'Value': u'65', u'Text': u'BURUNDI'},
      {u'Value': u'155', u'Text': u'BUTAN'},
      {u'Value': u'156', u'Text': u'CAD'},
      {u'Value': u'43', u'Text': u'CECENISTAN'},
      {u'Value': u'16', u'Text': u'CEK CUMHURIYETI'},
      {u'Value': u'86', u'Text': u'CEZAYIR'},
      {u'Value': u'160', u'Text': u'CIBUTI'},
      {u'Value': u'61', u'Text': u'CIN'},
      {u'Value': u'26', u'Text': u'DANIMARKA'},
      {u'Value': u'180', u'Text': u'DEMOKRATIK KONGO CUMHURIYETI'},
      {u'Value': u'176', u'Text': u'DOGU TIMOR'},
      {u'Value': u'123', u'Text': u'DOMINIK'},
      {u'Value': u'72', u'Text': u'DOMINIK CUMHURIYETI'},
      {u'Value': u'139', u'Text': u'EKVATOR'},
      {u'Value': u'63', u'Text': u'EKVATOR GINESI'},
      {u'Value': u'165', u'Text': u'EL SALVADOR'},
      {u'Value': u'117', u'Text': u'ENDONEZYA'},
      {u'Value': u'175', u'Text': u'ERITRE'},
      {u'Value': u'104', u'Text': u'ERMENISTAN'},
      {u'Value': u'6', u'Text': u'ESTONYA'},
      {u'Value': u'95', u'Text': u'ETYOPYA'},
      {u'Value': u'145', u'Text': u'FAS'},
      {u'Value': u'197', u'Text': u'FIJI'},
      {u'Value': u'120', u'Text': u'FILDISI SAHILI'},
      {u'Value': u'126', u'Text': u'FILIPINLER'},
      {u'Value': u'204', u'Text': u'FILISTIN'},
      {u'Value': u'41', u'Text': u'FINLANDIYA'},
      {u'Value': u'21', u'Text': u'FRANSA'},
      {u'Value': u'79', u'Text': u'GABON'},
      {u'Value': u'109', u'Text': u'GAMBIYA'},
      {u'Value': u'143', u'Text': u'GANA'},
      {u'Value': u'111', u'Text': u'GINE'},
      {u'Value': u'58', u'Text': u'GRANADA'},
      {u'Value': u'48', u'Text': u'GRONLAND'},
      {u'Value': u'171', u'Text': u'GUADELOPE'},
      {u'Value': u'169', u'Text': u'GUAM ADASI'},
      {u'Value': u'99', u'Text': u'GUATEMALA'},
      {u'Value': u'67', u'Text': u'GUNEY AFRIKA'},
      {u'Value': u'128', u'Text': u'GUNEY KORE'},
      {u'Value': u'62', u'Text': u'GURCISTAN'},
      {u'Value': u'82', u'Text': u'GUYANA'},
      {u'Value': u'70', u'Text': u'HAITI'},
      {u'Value': u'187', u'Text': u'HINDISTAN'},
      {u'Value': u'30', u'Text': u'HIRVATISTAN'},
      {u'Value': u'4', u'Text': u'HOLLANDA'},
      {u'Value': u'66', u'Text': u'HOLLANDA ANTILLERI'},
      {u'Value': u'105', u'Text': u'HONDURAS'},
      {u'Value': u'113', u'Text': u'HONG KONG'},
      {u'Value': u'15', u'Text': u'INGILTERE'},
      {u'Value': u'124', u'Text': u'IRAK'},
      {u'Value': u'202', u'Text': u'IRAN'},
      {u'Value': u'32', u'Text': u'IRLANDA'},
      {u'Value': u'23', u'Text': u'ISPANYA'},
      {u'Value': u'205', u'Text': u'ISRAIL'},
      {u'Value': u'12', u'Text': u'ISVEC'},
      {u'Value': u'49', u'Text': u'ISVICRE'},
      {u'Value': u'8', u'Text': u'ITALYA'},
      {u'Value': u'122', u'Text': u'IZLANDA'},
      {u'Value': u'119', u'Text': u'JAMAIKA'},
      {u'Value': u'116', u'Text': u'JAPONYA'},
      {u'Value': u'161', u'Text': u'KAMBOCYA'},
      {u'Value': u'184', u'Text': u'KAMERUN'},
      {u'Value': u'52', u'Text': u'KANADA'},
      {u'Value': u'34', u'Text': u'KARADAG'},
      {u'Value': u'94', u'Text': u'KATAR'},
      {u'Value': u'92', u'Text': u'KAZAKISTAN'},
      {u'Value': u'114', u'Text': u'KENYA'},
      {u'Value': u'168', u'Text': u'KIRGIZISTAN'},
      {u'Value': u'57', u'Text': u'KOLOMBIYA'},
      {u'Value': u'88', u'Text': u'KOMORLAR'},
      {u'Value': u'18', u'Text': u'KOSOVA'},
      {u'Value': u'162', u'Text': u'KOSTARIKA'},
      {u'Value': u'209', u'Text': u'KUBA'},
      {u'Value': u'206', u'Text': u'KUDUS'},
      {u'Value': u'133', u'Text': u'KUVEYT'},
      {u'Value': u'1', u'Text': u'KUZEY KIBRIS'},
      {u'Value': u'142', u'Text': u'KUZEY KORE'},
      {u'Value': u'134', u'Text': u'LAOS'},
      {u'Value': u'174', u'Text': u'LESOTO'},
      {u'Value': u'20', u'Text': u'LETONYA'},
      {u'Value': u'73', u'Text': u'LIBERYA'},
      {u'Value': u'203', u'Text': u'LIBYA'},
      {u'Value': u'38', u'Text': u'LIECHTENSTEIN'},
      {u'Value': u'47', u'Text': u'LITVANYA'},
      {u'Value': u'42', u'Text': u'LUBNAN'},
      {u'Value': u'31', u'Text': u'LUKSEMBURG'},
      {u'Value': u'7', u'Text': u'MACARISTAN'},
      {u'Value': u'98', u'Text': u'MADAGASKAR'},
      {u'Value': u'100', u'Text': u'MAKAO'},
      {u'Value': u'28', u'Text': u'MAKEDONYA'},
      {u'Value': u'55', u'Text': u'MALAVI'},
      {u'Value': u'103', u'Text': u'MALDIVLER'},
      {u'Value': u'107', u'Text': u'MALEZYA'},
      {u'Value': u'152', u'Text': u'MALI'},
      {u'Value': u'24', u'Text': u'MALTA'},
      {u'Value': u'87', u'Text': u'MARTINIK'},
      {u'Value': u'164', u'Text': u'MAURITIUS ADASI'},
      {u'Value': u'157', u'Text': u'MAYOTTE'},
      {u'Value': u'53', u'Text': u'MEKSIKA'},
      {u'Value': u'85', u'Text': u'MIKRONEZYA'},
      {u'Value': u'189', u'Text': u'MISIR'},
      {u'Value': u'60', u'Text': u'MOGOLISTAN'},
      {u'Value': u'46', u'Text': u'MOLDAVYA'},
      {u'Value': u'3', u'Text': u'MONAKO'},
      {u'Value': u'147', u'Text': u'MONTSERRAT (U.K.)'},
      {u'Value': u'106', u'Text': u'MORITANYA'},
      {u'Value': u'151', u'Text': u'MOZAMBIK'},
      {u'Value': u'196', u'Text': u'NAMBIYA'},
      {u'Value': u'76', u'Text': u'NEPAL'},
      {u'Value': u'84', u'Text': u'NIJER'},
      {u'Value': u'127', u'Text': u'NIJERYA'},
      {u'Value': u'141', u'Text': u'NIKARAGUA'},
      {u'Value': u'178', u'Text': u'NIUE'},
      {u'Value': u'36', u'Text': u'NORVEC'},
      {u'Value': u'80', u'Text': u'ORTA AFRIKA CUMHURIYETI'},
      {u'Value': u'131', u'Text': u'OZBEKISTAN'},
      {u'Value': u'77', u'Text': u'PAKISTAN'},
      {u'Value': u'149', u'Text': u'PALAU'},
      {u'Value': u'89', u'Text': u'PANAMA'},
      {u'Value': u'185', u'Text': u'PAPUA YENI GINE'},
      {u'Value': u'194', u'Text': u'PARAGUAY'},
      {u'Value': u'69', u'Text': u'PERU'},
      {u'Value': u'183', u'Text': u'PITCAIRN ADASI'},
      {u'Value': u'39', u'Text': u'POLONYA'},
      {u'Value': u'45', u'Text': u'PORTEKIZ'},
      {u'Value': u'68', u'Text': u'PORTO RIKO'},
      {u'Value': u'112', u'Text': u'REUNION'},
      {u'Value': u'37', u'Text': u'ROMANYA'},
      {u'Value': u'81', u'Text': u'RUANDA'},
      {u'Value': u'207', u'Text': u'RUSYA'},
      {u'Value': u'64', u'Text': u'S. ARABISTAN'},
      {u'Value': u'198', u'Text': u'SAMOA'},
      {u'Value': u'102', u'Text': u'SENEGAL'},
      {u'Value': u'138', u'Text': u'SEYSEL ADALARI'},
      {u'Value': u'200', u'Text': u'SILI'},
      {u'Value': u'179', u'Text': u'SINGAPUR'},
      {u'Value': u'27', u'Text': u'SIRBISTAN'},
      {u'Value': u'14', u'Text': u'SLOVAKYA'},
      {u'Value': u'19', u'Text': u'SLOVENYA'},
      {u'Value': u'150', u'Text': u'SOMALI'},
      {u'Value': u'74', u'Text': u'SRI LANKA'},
      {u'Value': u'129', u'Text': u'SUDAN'},
      {u'Value': u'172', u'Text': u'SURINAM'},
      {u'Value': u'191', u'Text': u'SURIYE'},
      {u'Value': u'163', u'Text': u'SVALBARD'},
      {u'Value': u'170', u'Text': u'SVAZILAND'},
      {u'Value': u'101', u'Text': u'TACIKISTAN'},
      {u'Value': u'110', u'Text': u'TANZANYA'},
      {u'Value': u'137', u'Text': u'TAYLAND'},
      {u'Value': u'108', u'Text': u'TAYVAN'},
      {u'Value': u'71', u'Text': u'TOGO'},
      {u'Value': u'130', u'Text': u'TONGA'},
      {u'Value': u'96', u'Text': u'TRINIDAT VE TOBAGO'},
      {u'Value': u'118', u'Text': u'TUNUS'},
      {u'Value': u'159', u'Text': u'TURKMENISTAN'},
      {u'Value': u'2', u'Text': u'TÜRKİYE'},
      {u'Value': u'75', u'Text': u'UGANDA'},
      {u'Value': u'40', u'Text': u'UKRAYNA'},
      {u'Value': u'29', u'Text': u'UKRAYNA-KIRIM'},
      {u'Value': u'173', u'Text': u'UMMAN'},
      {u'Value': u'192', u'Text': u'URDUN'},
      {u'Value': u'201', u'Text': u'URUGUAY'},
      {u'Value': u'56', u'Text': u'VANUATU'},
      {u'Value': u'10', u'Text': u'VATIKAN'},
      {u'Value': u'186', u'Text': u'VENEZUELA'},
      {u'Value': u'135', u'Text': u'VIETNAM'},
      {u'Value': u'148', u'Text': u'YEMEN'},
      {u'Value': u'115', u'Text': u'YENI KALEDONYA'},
      {u'Value': u'193', u'Text': u'YENI ZELLANDA'},
      {u'Value': u'144', u'Text': u'YESIL BURUN'},
      {u'Value': u'22', u'Text': u'YUNANISTAN'},
      {u'Value': u'158', u'Text': u'ZAMBIYA'},
      {u'Value': u'136', u'Text': u'ZIMBABVE'}]

if __name__ == '__main__':
    # print db
    data2json(db, 'ulkeler.json')
