#!/usr/bin/env python
# -*- coding: utf-8 -*-
# from 1 to 205

from tools.toolkits import data2json, filterize
from pprint import pprint

def ulkeDict(keys = []):
    db = {'33': u'ABD',
      '166': u'AFGANISTAN',
      '13': u'ALMANYA',
      '17': u'ANDORRA',
      '140': u'ANGOLA',
      '125': u'ANGUILLA',
      '90': u'ANTIGUA VE BARBUDA',
      '199': u'ARJANTIN',
      '25': u'ARNAVUTLUK',
      '153': u'ARUBA',
      '59': u'AVUSTRALYA',
      '35': u'AVUSTURYA',
      '5': u'AZERBAYCAN',
      '54': u'BAHAMALAR',
      '132': u'BAHREYN',
      '177': u'BANGLADES',
      '188': u'BARBADOS',
      '208': u'BELARUS',
      '11': u'BELCIKA',
      '182': u'BELIZE',
      '181': u'BENIN',
      '51': u'BERMUDA',
      '93': u'BIRLESIK ARAP EMIRLIGI',
      '83': u'BOLIVYA',
      '9': u'BOSNA HERSEK',
      '167': u'BOTSVANA',
      '146': u'BREZILYA',
      '97': u'BRUNEI',
      '44': u'BULGARISTAN',
      '91': u'BURKINA FASO',
      '154': u'BURMA (MYANMAR)',
      '65': u'BURUNDI',
      '155': u'BUTAN',
      '156': u'CAD',
      '43': u'CECENISTAN',
      '16': u'CEK CUMHURIYETI',
      '86': u'CEZAYIR',
      '160': u'CIBUTI',
      '61': u'CIN',
      '26': u'DANIMARKA',
      '180': u'DEMOKRATIK KONGO CUMHURIYETI',
      '176': u'DOGU TIMOR',
      '123': u'DOMINIK',
      '72': u'DOMINIK CUMHURIYETI',
      '139': u'EKVATOR',
      '63': u'EKVATOR GINESI',
      '165': u'EL SALVADOR',
      '117': u'ENDONEZYA',
      '175': u'ERITRE',
      '104': u'ERMENISTAN',
      '6': u'ESTONYA',
      '95': u'ETYOPYA',
      '145': u'FAS',
      '197': u'FIJI',
      '120': u'FILDISI SAHILI',
      '126': u'FILIPINLER',
      '204': u'FILISTIN',
      '41': u'FINLANDIYA',
      '21': u'FRANSA',
      '79': u'GABON',
      '109': u'GAMBIYA',
      '143': u'GANA',
      '111': u'GINE',
      '58': u'GRANADA',
      '48': u'GRONLAND',
      '171': u'GUADELOPE',
      '169': u'GUAM ADASI',
      '99': u'GUATEMALA',
      '67': u'GUNEY AFRIKA',
      '128': u'GUNEY KORE',
      '62': u'GURCISTAN',
      '82': u'GUYANA',
      '70': u'HAITI',
      '187': u'HINDISTAN',
      '30': u'HIRVATISTAN',
      '4': u'HOLLANDA',
      '66': u'HOLLANDA ANTILLERI',
      '105': u'HONDURAS',
      '113': u'HONG KONG',
      '15': u'INGILTERE',
      '124': u'IRAK',
      '202': u'IRAN',
      '32': u'IRLANDA',
      '23': u'ISPANYA',
      '205': u'ISRAIL',
      '12': u'ISVEC',
      '49': u'ISVICRE',
      '8': u'ITALYA',
      '122': u'IZLANDA',
      '119': u'JAMAIKA',
      '116': u'JAPONYA',
      '161': u'KAMBOCYA',
      '184': u'KAMERUN',
      '52': u'KANADA',
      '34': u'KARADAG',
      '94': u'KATAR',
      '92': u'KAZAKISTAN',
      '114': u'KENYA',
      '168': u'KIRGIZISTAN',
    '57': u'KOLOMBIYA',
    '88': u'KOMORLAR',
    '18': u'KOSOVA',
    '162': u'KOSTARIKA',
    '209': u'KUBA',
    '206': u'KUDUS',
    '133': u'KUVEYT',
    '1': u'KUZEY KIBRIS',
    '142': u'KUZEY KORE',
    '134': u'LAOS',
    '174': u'LESOTO',
    '20': u'LETONYA',
    '73': u'LIBERYA',
    '203': u'LIBYA',
    '38': u'LIECHTENSTEIN',
    '47': u'LITVANYA',
    '42': u'LUBNAN',
    '31': u'LUKSEMBURG',
    '7': u'MACARISTAN',
    '98': u'MADAGASKAR',
    '100': u'MAKAO',
    '28': u'MAKEDONYA',
    '55': u'MALAVI',
    '103': u'MALDIVLER',
    '107': u'MALEZYA',
    '152': u'MALI',
    '24': u'MALTA',
    '87': u'MARTINIK',
    '164': u'MAURITIUS ADASI',
    '157': u'MAYOTTE',
    '53': u'MEKSIKA',
    '85': u'MIKRONEZYA',
    '189': u'MISIR',
    '60': u'MOGOLISTAN',
    '46': u'MOLDAVYA',
    '3': u'MONAKO',
    '147': u'MONTSERRAT (U.K.)',
    '106': u'MORITANYA',
    '151': u'MOZAMBIK',
    '196': u'NAMBIYA',
    '76': u'NEPAL',
    '84': u'NIJER',
    '127': u'NIJERYA',
    '141': u'NIKARAGUA',
    '178': u'NIUE',
    '36': u'NORVEC',
    '80': u'ORTA AFRIKA CUMHURIYETI',
    '131': u'OZBEKISTAN',
    '77': u'PAKISTAN',
    '149': u'PALAU',
    '89': u'PANAMA',
    '185': u'PAPUA YENI GINE',
    '194': u'PARAGUAY',
    '69': u'PERU',
    '183': u'PITCAIRN ADASI',
    '39': u'POLONYA',
    '45': u'PORTEKIZ',
    '68': u'PORTO RIKO',
    '112': u'REUNION',
    '37': u'ROMANYA',
    '81': u'RUANDA',
    '207': u'RUSYA',
    '64': u'S. ARABISTAN',
    '198': u'SAMOA',
    '102': u'SENEGAL',
    '138': u'SEYSEL ADALARI',
    '200': u'SILI',
    '179': u'SINGAPUR',
    '27': u'SIRBISTAN',
    '14': u'SLOVAKYA',
    '19': u'SLOVENYA',
    '150': u'SOMALI',
    '74': u'SRI LANKA',
    '129': u'SUDAN',
    '172': u'SURINAM',
    '191': u'SURIYE',
    '163': u'SVALBARD',
    '170': u'SVAZILAND',
    '101': u'TACIKISTAN',
    '110': u'TANZANYA',
    '137': u'TAYLAND',
    '108': u'TAYVAN',
    '71': u'TOGO',
    '130': u'TONGA',
    '96': u'TRINIDAT VE TOBAGO',
    '118': u'TUNUS',
    '159': u'TURKMENISTAN',
    '2': u'TÜRKİYE',
    '75': u'UGANDA',
    '40': u'UKRAYNA',
    '29': u'UKRAYNA-KIRIM',
    '173': u'UMMAN',
    '192': u'URDUN',
    '201': u'URUGUAY',
    '56': u'VANUATU',
    '10': u'VATIKAN',
    '186': u'VENEZUELA',
    '135': u'VIETNAM',
    '148': u'YEMEN',
    '115': u'YENI KALEDONYA',
    '193': u'YENI ZELLANDA',
    '144': u'YESIL BURUN',
    '22': u'YUNANISTAN',
    '158': u'ZAMBIYA',
    '136': u'ZIMBABVE'}
    if not keys:
        data = {}
        for k,v  in  db.iteritems():
            data[k] = dict ( Text = v, Value = k, Childs= {} )
        return data
    else:
        selective = {}
        for key in keys:
            key = str(key)
            # selective[key] = db[key]
            selective[key] = dict( Text = db[key], Value = key, Childs = {})
        return selective


if __name__ == '__main__':
    # print db
    # data2json( ulkeDictDb() , '_json/ulkeler.json')
    # pprint ( filterize ( ulkeDictDb() ) )
    # pprint ( ulkeler() )
    pass
